services:
  gateway:
    build: ./gateway
    container_name: gateway
    env_file: .env
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082/udp"
    networks:
      - iot_net

  device:
    build: ./device
    env_file: .env
    # Nao mapeamos 'ports' aqui para evitar conflito na maquina fisica ao rodar multiplos devices
    networks:
      - iot_net

  client:
    build: ./client
    env_file: .env
    stdin_open: true
    tty: true
    networks:
      - iot_net

networks:
  iot_net:
    driver: bridge